### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by darsain** [darsain/laravel-console#13]
Catching all error types in this environment is just a nightmare.

Console needs to catch an error, put it into a profile with:

``` php
$profile = Darsain\Console\Console::getProfile(array(
  'error' => $error
));
```

And return the `$profile` object as JSON back to the client with 200 Status Code.

I was just not able to accomplish that. Barely kept my legs from breaking from all the logs thrown at them.

Error types to catch and properly handle:
- [x] Syntax errors.
- [x] Function/Class missing errors.
- [x] Thrown exceptions.

The core files responsible for execution are (really simple, just 2 classes with a couple of methods):
- console singleton (handles the execution and profile generation) is in [src/Darsain/Console/Console.php](https://github.com/Darsain/laravel-console/blob/master/src/Darsain/Console/Console.php).
- controller is in [src/controllers/ConsoleController.php](https://github.com/Darsain/laravel-console/blob/master/src/controllers/ConsoleController.php).

**Comment by sp0tteh** [comment]
Hey , thanks for this. Will check it out soon.

**Comment by darsain** [comment]
It feels hacky, but I think this might work.

**Comment by darsain** [comment]
None's complaining, seems to work well with everything I could throw at it ... I guess I'm gonna close this as fixed :)
