### ISSUE TITLE
Assets published with the wrong name

### ISSUE THREAD

**Issue by ajimix** [darsain/laravel-console#17]
After running the setup instructions, the assets folder created is called darsain/laravel-console as you can see in the result of `artisan asset:publish`

`Assets published for package: darsain/laravel-console`

But when I go to mydomain.com/console I see that the assets are being loaded from console folder instead of laravel-console so no assets are loaded.

I can easily fix that by renaming the folder but I think it's an issue.

**Comment by darsain** [comment]
Aaaah, my bad! But I'm gonna blame the lack of asset manager in L4... :)
