### ISSUE TITLE
installer broken

### ISSUE THREAD

**Issue by wishfoundry** [darsain/laravel-console#2]
artisan installer points to a dead link ( http://nodeload.github.com/Darsain/laravel-console/zipball/master )

**Comment by darsain** [comment]
Github nodeload server issue. Nothing to do with this bundle.

You have to use the alternative install method until it gets resolved, or install it manually.

**Comment by wishfoundry** [comment]
Not to be argumentative, but are you sure about that? I know they had some issues a few days ago, but today:
     https://status.github.com/

I thought the url just needed to be updated to :
    https://github.com/Darsain/laravel-console/archive/master.zip

**Comment by darsain** [comment]
@wishfoundry seems like GIthub changed zipball distribution or something, and Laravel's github provider (the code in artisan used to get stuff from github) needs to be updated.

http://forums.laravel.com/viewtopic.php?id=3322

Still not an issue of this repo :)
