### ISSUE TITLE
Reduce Font Size

### ISSUE THREAD

**Issue by mikeerickson** [darsain/laravel-console#20]
I would like to reduce the editor (and display) font size if possible.  I am sure I can find out where to hack this stuff out (probably in a css somewhere) but just curious if there was an exposed method for doing this?

If not, I can surely hack around and find out where to do it (heck, maybe even enhance to make this possible for others)

**Comment by darsain** [comment]
[public/css/main.css#L22](https://github.com/Darsain/laravel-console/blob/master/public/css/main.css#L22)

**Comment by mikeerickson** [comment]
So, that is one place (fixes the actual editor font) but how about in all the other output areas (and cursor)  Changing that one item causes issues elsewhere.    Is there _any_ type of override CSS I could create/modify as to not mess with the original code?

**Comment by darsain** [comment]
What are you talking about? Changing that one value propagates changes to all other sizes, as they all use `em` units relative to the body font-size. Just tried changing it to 14px and everything is OK, no issues, just smaller fonts.

The issues might arise when you are changing it in dev tools while app is running as it won't have a chance to recalculate positions of sections (I had to simulate flex box with JS to make it cross-browser compatible). Also make sure you are changing the `main.css` in `/public` directory, not `/vendor`

Anyway, the base font size is set to industry standard 1em (16px). It is nice and readable. I'm definitely not gonna change it, nor am I gonna add any arbitrary settings and pollute templates with `style=""` garbage just to cater to the needs of one man :) Sorry.

But if there is more demand for this, I'll reconsider. Meanwhile I'm closing this issue.

**Comment by mikeerickson** [comment]
I am not sure what the problem was before, but I managed to get this working.   So consider it cured (for me)
