### ISSUE TITLE
Routes do not work.

### ISSUE THREAD

**Issue by computeus** [darsain/laravel-console#27]
I am using Laravel 4.1.\* and installed the console.

Routes not working out of the box. I have to copy them to route.php file.

**Comment by darsain** [comment]
Can anyone point me to a problem? Haven't used Laravel in a while.

**Comment by computeus** [comment]
Hi,

After some digging I found that the problem is not related to laravel-console. I am using vagrant for my development and it seems server settings in vagrant causes this issue.

---

After some debugging it seems console_whitelist option creates this error.
