### ISSUE TITLE
Error when executing code

### ISSUE THREAD

**Issue by arne-s** [darsain/laravel-console#28]
When I click execute after entering code, I get this error:

```
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"syntax error, unexpected '\"', expecting T_STRING","file":"\/Users\/user\/www\/project\/vendor\/darsain\/laravel-console\/src\/Darsain\/Console\/Console.php(111) : eval()'d code","line":1}}
```

After adding _stripslashes()_ to the $code var method before eval(), the error goes away

I'm running Laravel on MacOS Mavericks, PHP 5.3 on MAMP

**Comment by darsain** [comment]
Do you have magic_quotes turned off?

**Comment by arne-s** [comment]
Yep, that was the problem. :)

**Comment by darsain** [comment]
K.
