### ISSUE TITLE
Cannot focus editor

### ISSUE THREAD

**Issue by szkuwa** [darsain/laravel-console#29]
No matter what I try I simply cannot focus editor (and write anything)
Tested with different browsers: 
Opera 12.16
Firefox 29.0
Chromium 34.0.1847.116
Chrome 35.0.1916.114
OS: Ubuntu 14.04

Does it require some specific version of flash/java/whatever?

//EDIT:
It seems to be a blade bug, after inspection I found that my compiled partials/head.blade.php looks like this:

``` html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Laravel Console</title>
        <meta name="viewport" content="width=device-width">

        <?php echo HTML::style('packages/darsain/laravel-console/css/normalize.css'); ?>
        <?php echo HTML::style('packages/darsain/laravel-console/css/main.css'); ?>
        {{ HTML::style('packages/darsain/laravel-console/css/codemirror.css') }}
        <?php echo HTML::style('packages/darsain/laravel-console/css/laravel.css'); ?>

        <?php echo HTML::script('packages/darsain/laravel-console/js/vendor/modernizr.js'); ?>
    </head>
    <body>
```

**Comment by darsain** [comment]
Any solutions? Or just wait for fix?

**Comment by szkuwa** [comment]
As I found out it's related to Blade and HHVM (https://github.com/facebook/hhvm/issues/2841), nothing to fix here. False alarm :)
