### ISSUE TITLE
Broken in 4.2?

### ISSUE THREAD

**Issue by newtonianb** [darsain/laravel-console#30]
When I try to call an Alias from console I get 

`Execution failed: 404 error`

**Comment by darsain** [comment]
No idea. Haven't used Laravel in a year. I'll have to look into changelogs and see what's causing the issue when I'll have some time. I don't know when that'll be, I have a lot on my to-do list right now.

Or you can look into it yourself and submit a PR? :)

**Comment by GrahamCampbell** [comment]
I can't replicate this.

**Comment by mlanin** [comment]
Had the same error. Problem was in the `console_whitelist` filter in `routes.php` file. There is an if condition that checks if your IP is in the whitelist (127.0.0.1 or ::1). So if you are using Laravel outside your local environment, you will always get 404. Maybe the best decision is to change this behaviour and check the environment.

**Comment by darsain** [comment]
> the best decision is to change this behaviour

That is there on purpose as console is the last page you want to have exposed from outside. I know that people will go against the bold texts and warnings and install this package on their production servers anyway, so this setting is necessary, and not going away.

So if this has been the issue, we know the cause now, and fix is modifying the whitelist config. If it was something else, feel free to comment and I'll reopen the issue.
