### ISSUE TITLE
How to use with Homestead?

### ISSUE THREAD

**Issue by carcinocron** [darsain/laravel-console#32]
It seems like this can't be used with Homestead. I think that it is because console restricts access only to 127.0.0.1/::1, but I can't find anything about how to edit the config without editing files in the vendor folder. This was working before I was using Homestead.

**Comment by GrahamCampbell** [comment]
Publish the config. This is standard for all laravel packages. See the laravel docs.

**Comment by darsain** [comment]
So I guess this is resolved? Feel free to reopen otherwise.
