### ISSUE TITLE
Display a list of executed SQL queries

### ISSUE THREAD

**Issue by darsain** [darsain/laravel-console#5]
Alongside execution times and used memory info, include a list of executed SQL queries and time they took to execute.

**Comment by darsain** [comment]
Event used for logging queries:

``` php
Event::listen('laravel.query', function($sql, $bindings, $time)
{
    // log somewhere
});
```

**Comment by markwu** [comment]
I just implemented this by myself, I attach the query result after the output result.  I will make a pull request to you later. 

Mark

**Comment by darsain** [comment]
I hope you like it :)

![Preview](http://i.imgur.com/u4UMQ.png)

**Comment by markwu** [comment]
So, cool! I really like it. Thanks!!!
